### DISCUSSION TITLE
`@Tag` annotation on Resource producer method

### DISCUSSION THREAD

**Discussion by gquintana** [eclipse/microprofile-open-api#571] [General]
I would like to place `@Tag` annotations from on a method producing a sub-resource:
```java
@Path("/search")
public class SearchResource {

  @Path("profile1")
  @Tag(name="Profile 1 Resource")
  public SearchResource searchProfile1() {
    return new SearchResource(profile1Config);
  }

  @Path("profile2")
  @Tag(name="Profile 2 Resource")
  public SearchResource searchProfile2() {
    return new SearchResource(profile2Config);
  }
```
`SearchResource` is JAX-RS resource class containing several operations.

The generated OpenAPI contracts contains:
```yaml
paths:
  /search/profile1/summary:
    get:
      tags:
      - Search Resource
  /search/profile1/detail:
    get:
      tags:
      - Search Resource
  /search/profile2/summary:
    get:
      tags:
      - Search Resource
  /search/profile2/detail:
    get:
      tags:
      - Search Resource
```
I expect tags to be _Profile 1 Resource_/_Profile 2 Resource_ not _Search Resource_

`@Tag` annotations are OK when placed at Resource class level or at Operation method level (a method returning content).
But they are not OK when placed at Sub-resource producer method level (a method returning a sub-resource).

Is it possible to configure tags using annotations when using sub-resource producer methods?

I am using Quarkus 3.2 with quarkus-smallrye-openapi extension.
