### ISSUE TITLE
Example object in Schema is always of String type

### ISSUE THREAD

**Issue by dmi3coder** [eclipse/microprofile-open-api#420]
The original issue was posted here: https://github.com/smallrye/smallrye-open-api/issues/300
I have a very simple User object where I have id field of type integer. I added example with specifying the type
``` java
public class User {

    @Schema(type = SchemaType.INTEGER, example = "1000")
    private Integer id;
... constructor, getters, and setters omitted
}
```
This generates a schema with an example as a string
```
    User:
      type: object
      properties:
        id:
          format: int32
          type: integer
          example: "1000"
```
Because of this in e.g Swagger UI when I'm prompted to fill in the example I have string type, users can think that it's mandatory to wrap integer into double-quotes.

By OpenAPI, an example can be any type of object(e.g integer, string, number), but currently, there's no way to specify that you want to parse this value into the required format. As I understand implementation doesn't know whether to parse this value or use it as a string.

As @MikeEdgar [suggested](https://github.com/smallrye/smallrye-open-api/issues/300#issuecomment-615180328): "Maybe the change could be to add to `@ExampleObject` a property `boolean parseValue` and support using that annotation from `@Schema`"
