### ISSUE TITLE
HeaderParam not generating parameter in spec

### ISSUE THREAD

**Issue by DaanA32** [eclipse/microprofile-open-api#572]
Hi all,

I cannot seem to generate a parameter for a HeaderParam.
It does work for query and cookie parameters:
```java
    public Response getUsers(
        @HeaderParam("Authorization") String authorizationHeader,
        @QueryParam("stringParam") String stringParam,
        @CookieParam("cookieParam") String cookieParam
    ) {
```
Generates:
```yaml
      parameters:
      -
        in: query
        name: stringParam
        schema:
          type: string
      -
        in: cookie
        name: cookieParam
        schema:
          type: string
```

It also does not generate when using `@Parameters`:
```java
    @Parameters({
            @Parameter(
                name = "Authorization",
                description = "Bearer token",
                required = true,
                schema = @Schema(type = SchemaType.STRING),
                in = ParameterIn.HEADER
            ),
            @Parameter(
                name = "stringParam",
                description = "String param",
                required = true,
                schema = @Schema(type = SchemaType.STRING),
                in = ParameterIn.QUERY
            ),
            @Parameter(
                name = "cookie",
                description = "COOKIE param",
                required = true,
                schema = @Schema(type = SchemaType.STRING),
                in = ParameterIn.COOKIE
            )
        })
```
Results in:
```yaml
      parameters:
      -
        description: String param
        in: query
        name: stringParam
        required: true
        schema:
          type: string
      -
        description: COOKIE param
        in: cookie
        name: cookie
        required: true
        schema:
          type: string
```

I'm using the following version:
```bash
build.date               2023-08-03 16:22:57 UTC
build.version            3.0.6
build.revision           0c0d6790
project.version          1.0-SNAPSHOT
project.helidon.version  3.2.2
project.flavor           MP
latest.helidon.version   4.0.0-RC1
default.helidon.version  3.2.2
```
